name: myfood

services:
  webapi:
    container_name: myfood-orders-webapi
    image: myfood.orders.webapi
    build:
      context: .
      dockerfile: src/Postech.Fiap.orders.WebApi/Dockerfile
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ASPNETCORE_URLS=https://+;http://+'
      - 'ASPNETCORE_Kestrel__Certificates__Default__Password=password123'
      - 'ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx'
      - 'DOTNET_USE_POLLING_FILE_WATCHER=true'
      - 'OTEL_EXPORTER_OTLP_ENDPOINT=http://myfood-seq:5341/ingest/otlp/v1/traces'
      - 'OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf'
    networks:
      - myfood-network
    ports:
      - "5095:80"
      - "7031:443"
    volumes:
      - '$USERPROFILE\.aspnet\https:/https/'
    depends_on:
      - postgres

  postgres:
    container_name: myfood-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: myfooduser
      POSTGRES_PASSWORD: blueScreen@666
      POSTGRES_DB: myfooddb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myfood-network

  seq:
    container_name: myfood-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 3380:80
    networks:
      - myfood-network

volumes:
  postgres-data:

networks:
  myfood-network:
    driver: bridge