apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders-webapi.fullname" . }}
  labels:
    {{- include "orders-webapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orders-webapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orders-webapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ConnectionStrings__SQLConnection
              valueFrom:
                configMapKeyRef:
                  name: myfood-db-orders-config
                  key: ConnectionStrings__SQLConnection
            - name: AzureStorageSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: myfood-storage-account-config
                  key: AzureStorageSettings__ConnectionString
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 60
          resources:
          {{- toYaml .Values.resources | nindent 12 }}